export const companyData = [
    {
        id:'0',
        fid: 0,
        companyName: 'Company 1',
        description: 'Faço xyz',
        rating: 3,
        verifiedAddresses: {},
    },
    {
        id:'1',
        fid: 0,
        companyName: 'Company 2',
        description: 'Faço xyz',
        rating: 3,
        verifiedAddresses: {},
    },
    {
        id:'2',
        fid: 0,
        companyName: 'Company 3',
        description: 'Faço xyz',
        rating: 3,
        verifiedAddresses: {},
    },
    {
        id:'3',
        fid: 0,
        companyName: 'Company 4',
        description: 'Faço xyz',
        rating: 3,
        verifiedAddresses: {},
    },
    {
        id:'4',
        fid: 0,
        companyName: 'Company 5',
        description: 'Faço xyz',
        rating: 3,
        verifiedAddresses: {},
    },
    {
        id:'5',
        fid: 0,
        companyName: 'Company 6',
        description: 'Faço xyz',
        rating: 3,
        verifiedAddresses: {},
    },
    {
        id:'6',
        fid: 0,
        companyName: 'Company 7',
        description: 'Faço xyz',
        rating: 3,
        verifiedAddresses: {},
    },
    {
        id:'7',
        fid: 0,
        companyName: 'Company 8',
        description: 'Faço xyz',
        rating: 3,
        verifiedAddresses: {},
    },
    {
        id:'8',
        fid: 0,
        companyName: 'Company 9',
        description: 'Faço xyz',
        rating: 3,
        verifiedAddresses: {},
    },
    {
        id:'9',
        fid: 0,
        companyName: 'Company 10',
        description: 'Faço xyz',
        rating: 3,
        verifiedAddresses: {},
    }
];